### ISSUE TITLE
will it work with python3.2?

### ISSUE THREAD

**Issue by sander76** [petervizi/python-eeml#12]
I've been going through the documentation, but can't seem to find anything on the python versions....
Thanks !

**Comment by petervizi** [comment]
Sander, I can't think of any obvious reason why it shouldn't work, I haven't tried it with 3.2 though. Please give feedback if you encounter any problem.

**Comment by sander76** [comment]
Hi Peter,

I saw a forum topic stating python3 was not working...
http://www.raspberrypi.org/phpBB3/viewtopic.php?t=11968&p=129437

I could have tried myself, but as the topic is very recent I thought I'd ask before trying myself....

Sander.

**Comment by petervizi** [comment]
Thanks for bringing that issue to my attention, I'll look into it.

**Comment by petervizi** [comment]
Sander,

Could you please try version 2.0.0 in your environment and report any issues?

Thanks,
Peter

**Comment by sander76** [comment]
Okay. I will. Unfortunately I will start having time at the end of next
week. I'll keep you posted. I guess it is also a good idea to post a
message on the forum where the issue was reported the first time.
Thanks !

Sander
