### ISSUE TITLE
Support for other units?

### ISSUE THREAD

**Issue by electrodynatronic** [petervizi/python-eeml#14]
Hey, thanks for putting this out. Was just exactly what I needed. I added a Bogus unit to my local copy for testing. Do you plan to add support for additional units? Unit-less quantities?  Would you like others to contribute? Cheers.

class Bogus(Unit):
    """
    This is the Bogus unit class.
    """

```
def __init__(self):
    """
    Initialize the `Unit` parameters with Bogus.
    """
    Unit.__init__(self, 'Bogus', 'derivedSI', u'!')
```

**Comment by petervizi** [comment]
Hi, 

I haven't realy planned to put too much effort into including all units, as your example shows a simple three-liner is enough to use whatever you like. But of course you are welcomed to submit patches to this lib. I'm looking forward to it!
