### ISSUE TITLE
CosmError: XML Parser Error: Duplicate datastream ids

### ISSUE THREAD

**Issue by jolcese** [petervizi/python-eeml#23]
I'm looping between a pac.update and almost 1 out of 2 pac.put() will fail with this error: CosmError: XML Parser Error: Duplicate datastream ids

I can see on the cosm debug a successfull push:
&lt;eeml xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://www.eeml.org/xsd/0.5.1&quot; xsi:schemaLocation=&quot;http://www.eeml.org/xsd/0.5.1 http://www.eeml.org/xsd/0.5.1/0.5.1.xsd&quot; version=&quot;0.5.1&quot;&gt;&lt;environment&gt;&lt;data id=&quot;1&quot;&gt;&lt;current_value&gt;1161.71&lt;/current_value&gt;&lt;unit type=&quot;derivedSI&quot; symbol=&quot;W&quot;&gt;Watt&lt;/unit&gt;&lt;/data&gt;&lt;data id=&quot;3&quot;&gt;&lt;current_value&gt;1187.12&lt;/current_value&gt;&lt;unit type=&quot;derivedSI&quot; symbol=&quot;VA&quot;&gt;VoltAmpere&lt;/unit&gt;&lt;/data&gt;&lt;data id=&quot;2&quot;&gt;&lt;current_value&gt;464.41&lt;/current_value&gt;&lt;unit type=&quot;derivedSI&quot; symbol=&quot;kWh&quot;&gt;WattHour&lt;/unit&gt;&lt;/data&gt;&lt;data id=&quot;0&quot;&gt;&lt;current_value&gt;5183.06&lt;/current_value&gt;&lt;unit type=&quot;basicSI&quot; symbol=&quot;mA&quot;&gt;Ampere&lt;/unit&gt;&lt;/data&gt;&lt;data id=&quot;5&quot;&gt;&lt;current_value&gt;229.04&lt;/current_value&gt;&lt;unit type=&quot;derivedSI&quot; symbol=&quot;V&quot;&gt;Volt&lt;/unit&gt;&lt;/data&gt;&lt;data id=&quot;4&quot;&gt;&lt;current_value&gt;0.97&lt;/current_value&gt;&lt;/data&gt;&lt;/environment&gt;&lt;/eeml&gt;

But the following push fails with 400:
&lt;eeml xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://www.eeml.org/xsd/0.5.1&quot; xsi:schemaLocation=&quot;http://www.eeml.org/xsd/0.5.1 http://www.eeml.org/xsd/0.5.1/0.5.1.xsd&quot; version=&quot;0.5.1&quot;&gt;&lt;environment&gt;&lt;data id=&quot;1&quot;&gt;&lt;current_value&gt;1161.71&lt;/current_value&gt;&lt;unit type=&quot;derivedSI&quot; symbol=&quot;W&quot;&gt;Watt&lt;/unit&gt;&lt;/data&gt;&lt;data id=&quot;3&quot;&gt;&lt;current_value&gt;1187.12&lt;/current_value&gt;&lt;unit type=&quot;derivedSI&quot; symbol=&quot;VA&quot;&gt;VoltAmpere&lt;/unit&gt;&lt;/data&gt;&lt;data id=&quot;2&quot;&gt;&lt;current_value&gt;464.41&lt;/current_value&gt;&lt;unit type=&quot;derivedSI&quot; symbol=&quot;kWh&quot;&gt;WattHour&lt;/unit&gt;&lt;/data&gt;&lt;data id=&quot;0&quot;&gt;&lt;current_value&gt;5183.06&lt;/current_value&gt;&lt;unit type=&quot;basicSI&quot; symbol=&quot;mA&quot;&gt;Ampere&lt;/unit&gt;&lt;/data&gt;&lt;data id=&quot;5&quot;&gt;&lt;current_value&gt;229.04&lt;/current_value&gt;&lt;unit type=&quot;derivedSI&quot; symbol=&quot;V&quot;&gt;Volt&lt;/unit&gt;&lt;/data&gt;&lt;data id=&quot;4&quot;&gt;&lt;current_value&gt;0.97&lt;/current_value&gt;&lt;/data&gt;&lt;data id=&quot;1&quot;&gt;&lt;current_value&gt;1182.68&lt;/current_value&gt;&lt;unit type=&quot;derivedSI&quot; symbol=&quot;W&quot;&gt;Watt&lt;/unit&gt;&lt;/data&gt;&lt;data id=&quot;3&quot;&gt;&lt;current_value&gt;1213.19&lt;/current_value&gt;&lt;unit type=&quot;derivedSI&quot; symbol=&quot;VA&quot;&gt;VoltAmpere&lt;/unit&gt;&lt;/data&gt;&lt;data id=&quot;2&quot;&gt;&lt;current_value&gt;464.41&lt;/current_value&gt;&lt;unit type=&quot;derivedSI&quot; symbol=&quot;kWh&quot;&gt;WattHour&lt;/unit&gt;&lt;/data&gt;&lt;data id=&quot;0&quot;&gt;&lt;current_value&gt;5301.12&lt;/current_value&gt;&lt;unit type=&quot;basicSI&quot; symbol=&quot;mA&quot;&gt;Ampere&lt;/unit&gt;&lt;/data&gt;&lt;data id=&quot;5&quot;&gt;&lt;current_value&gt;228.85&lt;/current_value&gt;&lt;unit type=&quot;derivedSI&quot; symbol=&quot;V&quot;&gt;Volt&lt;/unit&gt;&lt;/data&gt;&lt;data id=&quot;4&quot;&gt;&lt;current_value&gt;0.97&lt;/current_value&gt;&lt;/data&gt;&lt;/environment&gt;&lt;/eeml&gt;

This is because dapoints from previous version are also included.

**Comment by petervizi** [comment]
Hi jolcese, 

Thanks for reporting this. The issue comes from the fact that Data objects are stored in a list and an update only appends to that. It's quite trivial to change the data structure to a map, keyed by Data's id. Will keep you posted.

**Comment by jolcese** [comment]
Hi Peter,
Thanks a lot for looking into this.
BTW, really great work!
Jose

_J+_
