### ISSUE TITLE
XSD schema validaton for "id" breaks Cosm compatibility

### ISSUE THREAD

**Issue by jolcese** [petervizi/python-eeml#24]
Cosm currently does not enforce "id" to be nonNegativeInteger (per EEML 0.5.1) so commit c75e280bdcc2e8e171dbae527cf18e4bff5d03ce breaks previous Datastreams with String identifiers. Those can't be updated any longer.

**Comment by petervizi** [comment]
Hi Jose, 

I'm assuming you are referring to the id of the data element - environment also has a non negative although optional id -, and what I see is `type="xsd:nonNegativeInteger"` and `use="required"` in line 132 of the schema. Can you please double check? 

Thanks

**Comment by jolcese** [comment]
That's right. It's the id of the Data element.

I used to use:
                    pac.update([eeml.Data("Power", power,
unit=eeml.Unit('Watt','derivedSI','W')),
                                eeml.Data("PowerApparent", powerapparent,
unit=eeml.Unit('VoltAmpere','derivedSI','VA')),
                                eeml.Data("PowerAccumulated", poweracc,
unit=eeml.Unit('WattHour','derivedSI','kWh')),
                                eeml.Data("Current", current,
unit=eeml.Unit('Ampere','basicSI','mA')),
                                eeml.Data("Voltage", voltage,
unit=eeml.Unit('Volt','derivedSI','V')),
                                eeml.Data("PowerFactor", powerfactor)])

<eeml xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xmlns="http://www.eeml.org/xsd/0.5.1"
xsi:schemaLocation="http://www.eeml.org/xsd/0.5.1
http://www.eeml.org/xsd/0.5.1/0.5.1.xsd"
version="0.5.1"><environment><data
id="Power"><current_value>532.78</current_value><unit type="derivedSI"
symbol="W">Watt</unit></data><data
id="PowerApparent"><current_value>716.33</current_value><unit
type="derivedSI" symbol="VA">VoltAmpere</unit></data><data
id="PowerAccumulated"><current_value>467.27</current_value><unit
type="derivedSI" symbol="kWh">WattHour</unit></data><data
id="Current"><current_value>3182.36</current_value><unit
type="basicSI" symbol="mA">Ampere</unit></data><data
id="Voltage"><current_value>225.09</current_value><unit
type="derivedSI" symbol="V">Volt</unit></data><data
id="PowerFactor"><current_value>0.74</current_value></data></environment></eeml>

But now I need to use:
                    pac.update([eeml.Data(0, power,
unit=eeml.Unit('Watt','derivedSI','W')),
                                eeml.Data(1, powerapparent,
unit=eeml.Unit('VoltAmpere','derivedSI','VA')),
                                eeml.Data(2, poweracc,
unit=eeml.Unit('WattHour','derivedSI','kWh')),
                                eeml.Data(3, current,
unit=eeml.Unit('Ampere','basicSI','mA')),
                                eeml.Data(4, voltage,
unit=eeml.Unit('Volt','derivedSI','V')),
                                eeml.Data(5, powerfactor)])

<eeml xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xmlns="http://www.eeml.org/xsd/0.5.1"
xsi:schemaLocation="http://www.eeml.org/xsd/0.5.1
http://www.eeml.org/xsd/0.5.1/0.5.1.xsd"
version="0.5.1"><environment><data
id=0><current_value>532.78</current_value><unit type="derivedSI"
symbol="W">Watt</unit></data><data
id=1><current_value>716.33</current_value><unit type="derivedSI"
symbol="VA">VoltAmpere</unit></data><data
id=2><current_value>467.27</current_value><unit type="derivedSI"
symbol="kWh">WattHour</unit></data><data
id=3><current_value>3182.36</current_value><unit type="basicSI"
symbol="mA">Ampere</unit></data><data
id=4><current_value>225.09</current_value><unit type="derivedSI"
symbol="V">Volt</unit></data><data
id=5><current_value>0.74</current_value></data></environment></eeml>

_J+_

**Comment by petervizi** [comment]
So do we agree that prior to version 4.0.0 the generated xml wasn't valid eeml? If so I'll close this ticket.

**Comment by jolcese** [comment]
Yes, I agree that it wasn't a valid eeml. However I suggest to add some
mechanism to allow these non-valid eeml in order to be able to still
communicate with Cosm :)

_J+_

**Comment by petervizi** [comment]
Sorry for the slow turnaround. Can you give the Invalidator a try to see if it fits your use case?
