### ISSUE TITLE
 exception_example.py module import error

### ISSUE THREAD

**Issue by thewebtor** [petervizi/python-eeml#28]
In exception_example.py

Line 5 reads:
  from eeml import CosmError

This generates an error: 
  ImportError: cannot import name CosmError

The code works when changed into: 
  from eeml.datastream import CosmError

This is probably a bug.

Platform: Raspberry Pi with Raspbian (updated yy130420).

**Comment by petervizi** [comment]
Fixed in 680c3abbac4186bb8ae9c155feaee345aa086836
