### ISSUE TITLE
s/Pachube/cosm

### ISSUE THREAD

**Issue by rinchen** [petervizi/python-eeml#8]
Hi,

Need to change the api call and associated comments from Pachube to COSM as per 11 May 2012 announcement by them.

J

**Comment by petervizi** [comment]
Thanks Joey, let me know if you have issues with the update.

**Comment by rinchen** [comment]
I've applied the change but there is something amiss. My feed isn't updating and I'm not getting any errors in the log that I can see.  The cosm debug log says I'm not making any requests.  The program I use (see http://radmon.stan4d.net/ for the code) also sends up tweets and those are working but cosm posting is not.

**Comment by rinchen** [comment]
It's throwing errors now which is good for debugging :-)  

type 'exceptions.AttributeError'

**Comment by rinchen** [comment]
```
pac = eeml.cosm(API_URL, API_KEY)
```

AttributeError: 'module' object has no attribute 'cosm'

**Comment by rinchen** [comment]
Well, I suspect this was me  doing a s/pachube/cosm but the actual change was s/pachube/Cosm with a capital C.
