### ISSUE TITLE
raise library specific exceptions

### ISSUE THREAD

**Issue by ponty** [petervizi/python-eeml#9]
It would be better if I could catch a library specific exception in case of communication error.
This is my code now, it caches everything:

``` python
    pa = eeml.Pachube(feed, key)
    pa.update([eeml.Data(stream, round(x.celsius, 1), unit=Celsius()), ])
    try:
        pa.put()
    except Exception, e:
    # better: except PachubeError, e:
        print e
```

library specific exception examples:
http://docs.python.org/tutorial/errors.html#user-defined-exceptions

**Comment by petervizi** [comment]
Hi ponty, 

Can you provide a patch for this? 

Peter

**Comment by petervizi** [comment]
Thanks, it's merged.
